In [55]:
import torch
import torch.optim as optim

In [56]:
torch.manual_seed(1)

In [57]:
x_train = torch.FloatTensor([[1], [2], [3],[4]])
y_train = torch.FloatTensor([[2], [4], [6],[8]])
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.],
        [4.]])
torch.Size([4, 1])


In [58]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.],
        [8.]])
torch.Size([4, 1])


In [59]:
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함.
W = torch.zeros(1, requires_grad=True) 
# 가중치 W를 출력
print(W) 

tensor([0.], requires_grad=True)


In [60]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [61]:
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

In [62]:
nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1999 W: 0.300, b: 0.100 Cost: 30.000000
Epoch  100/1999 W: 1.847, b: 0.450 Cost: 0.034085
Epoch  200/1999 W: 1.886, b: 0.334 Cost: 0.018712
Epoch  300/1999 W: 1.916, b: 0.247 Cost: 0.010273
Epoch  400/1999 W: 1.938, b: 0.183 Cost: 0.005640
Epoch  500/1999 W: 1.954, b: 0.136 Cost: 0.003096
Epoch  600/1999 W: 1.966, b: 0.101 Cost: 0.001700
Epoch  700/1999 W: 1.975, b: 0.075 Cost: 0.000933
Epoch  800/1999 W: 1.981, b: 0.055 Cost: 0.000512
Epoch  900/1999 W: 1.986, b: 0.041 Cost: 0.000281
Epoch 1000/1999 W: 1.990, b: 0.030 Cost: 0.000154
Epoch 1100/1999 W: 1.992, b: 0.022 Cost: 0.000085
Epoch 1200/1999 W: 1.994, b: 0.017 Cost: 0.000047
Epoch 1300/1999 W: 1.996, b: 0.012 Cost: 0.000026
Epoch 1400/1999 W: 1.997, b: 0.009 Cost: 0.000014
Epoch 1500/1999 W: 1.998, b: 0.007 Cost: 0.000008
Epoch 1600/1999 W: 1.998, b: 0.005 Cost: 0.000004
Epoch 1700/1999 W: 1.999, b: 0.004 Cost: 0.000002
Epoch 1800/1999 W: 1.999, b: 0.003 Cost: 0.000001
Epoch 1900/1999 W: 1.999, b: 0.002 Cost: 0.000001

# nn.Module로 구현하는 선형 회귀

In [63]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [64]:
torch.manual_seed(1)

In [65]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [66]:
# 모델을 선언 및 초기화. 단순 선형 회귀이므로 input_dim=1, output_dim=1.
model = nn.Linear(1,1)

In [67]:
print(list(model.parameters())) # 첫번째 값이 W고, 두번째 값이 b에 해당

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [68]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

In [69]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.103540
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [70]:
# 임의의 입력 4를 선언
new_var =  torch.FloatTensor([[4.0]]) 
# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) # forward 연산
# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print("훈련 후 입력이 4일 때의 예측값 :", pred_y) 

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9989]], grad_fn=<AddmmBackward>)


In [71]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]
